### ISSUE TITLE
How to add a fake obstacle in rosweb?

### ISSUE THREAD

**Issue by SonOfSunny** [rbonghi/ros_webconsole#3]
I have saw your video in youtube https://www.youtube.com/watch?v=rzTBSHTWRxg , I am confused with how to edit a  map in nav2d viewer and make the robot to  avoid obstacle , really thank you for your reply

**Comment by rbonghi** [comment]
Hi @SonOfSunny, I've written a JS library to edit the map from the website and a controller in ROS to fuse different information from all sensor and the Web controller.

The library is https://github.com/rbonghi/rosmapjs but in the last two years I've worked in other robotics problem.
It's planned to restart of this project in the next weeks :-)
