### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by mpena2099** [rbonghi/ros_webconsole#4]
Hi!

The demo (http://rbonghi.github.io/roswebconsole/) is not working. From webconsole: "Firefox can’t establish a connection to the server at ws://demo.robotwebtools.org:9090/."

Thanks,
Mauricio

**Comment by rbonghi** [comment]
Hi @mpena2099 

Like the other issue #5 I'm working for a new version, you can test here:
https://rbonghi.github.io/ros_webconsole/
